### ISSUE TITLE
When uses custom view...

### ISSUE THREAD

**Issue by pangpingfei** [eilianlove/EmptyKit#1]
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000284060 UIView:0x7fab1b4063a0.centerY == EmptyKit.EmptyView:0x7fab1b40a520.centerY - 44   (active)>",
    "<NSLayoutConstraint:0x600000283c00 V:|-(0)-[UIView:0x7fab1b4063a0]   (active, names: '|':EmptyKit.EmptyView:0x7fab1b40a520 )>",
    "<NSLayoutConstraint:0x600000284380 V:[UIView:0x7fab1b4063a0]-(0)-|   (active, names: '|':EmptyKit.EmptyView:0x7fab1b40a520 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000284060 UIView:0x7fab1b4063a0.centerY == EmptyKit.EmptyView:0x7fab1b40a520.centerY - 44   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by ZionChang** [comment]
Can you describe more specific? Which version do you use?

**Comment by pangpingfei** [comment]
It's solved after updated to the lastest version...Thanks.
