### ISSUE TITLE
显示状态时候使用MJ下拉刷新造成当前视图向上偏移大约40像素

### ISSUE THREAD

**Issue by ChinaArJun** [eilianlove/EmptyKit#11]
显示状态时候使用MJ下拉刷新造成当前视图向上偏移大约40像素

**Comment by ZionChang** [comment]
当前视图是指emptyView还是你本身的视图？

**Comment by ChinaArJun** [comment]
指emptyView

**Comment by ZionChang** [comment]
有demo吗？
然后`verticalOffsetForEmpty`这个代理可以调节偏移量

**Comment by CivelXu** [comment]
这是个 bug 呀   用MJ下拉刷新 之前 位置是正确的  刷新之后 空数据  出现 上偏移大约40像素

**Comment by ZionChang** [comment]
@CivelXu 我试了下，没问题，要不然你发给demo给我，我看看呢
