### ISSUE TITLE
Need customised button

### ISSUE THREAD

**Issue by DesmondPang** [eilianlove/EmptyKit#12]
How to customise the button? For example, add cornerRadius.

**Comment by ZionChang** [comment]
For now, it doesn't support changing some button's properties which don't mention in `EmptyDataSource`.
So if you want to customize button, there are two ways may be help you.
1. Get the emptyView from tableView's subviews, then use `KVO` to get button.
2. Use `customViewForEmpty` to customize your emptyView.

Anyway, I'll think about how to make it easy to customize properties of `EmptyKit`, maybe next version.

**Comment by icefox57** [comment]
same request , button need customization .

**Comment by ZionChang** [comment]
I think there are so many methods of datasource which is annoying. For now I have to add method to customize button.
I want it to be simple, so it will be great if you have some advice

**Comment by imWalsh** [comment]
同样需求 ，不过我是改了代码 ，
 在 delegate 的 emptyWillAppear  暴露出自己，然后 获取 button 设置就行了 ，希望采纳

**Comment by ZionChang** [comment]
我会单独开个issue来解决你们需要解决的问题，最近也在考虑重构
(I'd like to reopen a new issue to solve your requirement, and I'm thinking code refactoring)
