### ISSUE TITLE
Question: How to avoid cover the header view

### ISSUE THREAD

**Issue by CivelXu** [eilianlove/EmptyKit#14]
How to avoid cover the tableview header view ?

**Comment by ZionChang** [comment]
I can't understand what you mean?

**Comment by CivelXu** [comment]
the empty placeHolder view covered my tableviewHeader view
How to fix it

**Comment by ZionChang** [comment]
Both emptyView and tableviewHeader show, that's weird!
Could you send me a demo or some code, I never meet this.

**Comment by CivelXu** [comment]
In a TableView (with tableViewHeader) ,The  EmptyKit view will covered  all the screen, I set the emptyKit  view background color clear , the tableViewHeader can be seen.

**Comment by ZionChang** [comment]
Please send me a demo, acherzz.work@gmail.com, I'm a little busy, thanks
