### ISSUE TITLE
3.0.3 broke tableView.reloadData()

### ISSUE THREAD

**Issue by wousser** [eilianlove/EmptyKit#2]
In the most recent version of EmptyKit, the empty view does not remove when reloading tableview with function tableView.reloadData(). Also forcing the update by tableView.ept.reloadData() still keeps the empty view. When the viewController is viewed again, this is solved.

This also happens in the demo project. Running on simulator and iOS 10. (Version 10.0 (SimulatorApp-726.7 
![simulator screen shot jan 10 2017 01 57 42](https://cloud.githubusercontent.com/assets/1159336/21777062/351d327a-d6d8-11e6-9a25-f9ddd29ac566.png)
)

**Comment by ZionChang** [comment]
Thanks for the issue, it should be solved in 3.0.4
