### ISSUE TITLE
Vertical alignment does not take into account tableheaderview

### ISSUE THREAD

**Issue by wousser** [eilianlove/EmptyKit#3]
When adding a tableheaderview, the empty view is not aligned correctly, the image is overlapping the tableheaderview. Is this an issue or should this be adjusted using offset?

To reproduce in the example project:

`override func viewDidLoad() {
        super.viewDidLoad()
        tableView.tableFooterView = UIView()
        tableView.tableHeaderView = UIView.init(frame: CGRect.init(x: 0, y: 0, width: 300, height: 150))
        tableView.tableHeaderView?.backgroundColor = UIColor.black
        setupEmpty()
    }`

![simulator screen shot jan 16 2017 09 02 12](https://cloud.githubusercontent.com/assets/1159336/21967961/81551f6c-dbca-11e6-8f28-e7166f7c8d1b.png)

**Comment by ZionChang** [comment]
It should be solved in 3.0.5 🍺
