### ISSUE TITLE
AutoreleasingUnsafeMutablePointer

### ISSUE THREAD

**Issue by difoi** [eilianlove/EmptyKit#7]
Cannot convert value of type 'AutoreleasingUnsafeMutablePointer<AnyClass>' (aka 'AutoreleasingUnsafeMutablePointer<AnyObject.Type>') to expected argument type 'AutoreleasingUnsafeMutablePointer<AnyClass?>!' (aka 'ImplicitlyUnwrappedOptional<AutoreleasingUnsafeMutablePointer<Optional<AnyObject.Type>>>')

**Comment by ZionChang** [comment]
How did this happen?

**Comment by ZionChang** [comment]
I have to close it since there is no response
