### ISSUE TITLE
请问如何解决设置了无数据图片后，在有数据的页面首次加载会闪一下显示这个无数据图片的问题？

### ISSUE THREAD

**Issue by qiu1993** [eilianlove/EmptyKit#8]
tableView设置了无数据图片后，第一次加载时，会闪一下、也就是reloadData后显示数据之前，先加载无数据页面。

**Comment by ZionChang** [comment]
你的意思是你开始没有数据，然后网络请求回来之前的这个loading状态？

**Comment by qiu1993** [comment]
对，这个设置了图片就会一闪而过。但是再次下拉刷新就没有，仅限于每个页面切换时首次加载

**Comment by ZionChang** [comment]
那你想显示什么，如果网络慢，你们的数据不是都没回来吗？应该在添加一个属性记录网络是loading还是success，然后通过customViewForEmpty来设置，如果是loading则显示loading的一个view，否则就return nil就走本身的一套了。
如果你不想显示则可以通过emptyShouldDisplay来判断
