### ISSUE TITLE
忽略section后，不能滚动了

### ISSUE THREAD

**Issue by LJjack** [eilianlove/EmptyKit#9]
使用sectionsToIgnore虽然能够显示空样式，但是不能滚动了

**Comment by ZionChang** [comment]
Can you show me a demo or some code, because I didn't find the issue you said. 😊

**Comment by LJjack** [comment]
func numberOfSections(in collectionView: UICollectionView) -> Int {
            return 2
    }
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if section == 0 {
           
            return 0
        }
        return 6
    }



    func sectionsToIgnore(in view: UIView) -> [Int]? {
        return [1]
    }

**Comment by ZionChang** [comment]
You mean `collectionView?.alwaysBounceVertical = true`?

**Comment by LJjack** [comment]
Demo怎么发给您呢？

**Comment by ZionChang** [comment]
archerzz.work@gmail.com

**Comment by LJjack** [comment]
发给您了，麻烦您看一下，谢谢

**Comment by ZionChang** [comment]
This is not a issue of EmptyKit, I'll close it.
